% Функции

К этому моменту вы уже видели одну функцию, `main`:

```rust
fn main() {
}
```

Это - простейшее объявление функции. Как мы упоминали ранее, ключевое слово `fn`
объявляет функцию. За ним следует её имя, пустые круглые скобки (поскольку эта
функция не принимает аргументов), а затем тело функции, заключённое в фигурные
скобки. Вот функция `foo`:

```rust
fn foo() {
}
```

Итак, что насчёт аргументов, принимаемых функцией? Вот функция, печатающая
число:

```rust
fn print_number(x: i32) {
    println!("x равен: {}", x);
}
```

Вот полная программа, использующая функцию `print_number`:

```rust
fn main() {
    print_number(5);
}

fn print_number(x: i32) {
    println!("x равен: {}", x);
}
```

Как видите, аргументы функций похожи на операторы `let`: вы можете объявить тип
аргумента после двоеточия.

Вот полная программа, которая складывает два числа и печатает их:

```rust
fn main() {
    print_sum(5, 6);
}

fn print_sum(x: i32, y: i32) {
    println!("сумма чисел: {}", x + y);
}
```

Аргументы разделяются запятой - и при вызове функции, и при её объявлении.

В отличие от `let`, вы _должны_ объявлять типы аргументов функции. Этот код не
скомпилируется:

```{rust,ignore}
fn print_sum(x, y) {
    println!("sum is: {}", x + y);
}
```

Вы увидите такую ошибку:

```text
hello.rs:5:18: 5:19 expected one of `!`, `:`, or `@`, found `)`
hello.rs:5 fn print_number(x, y) {
```

Это осознанное решение при проектировании языка. Бесспорно, вывод типов во всей
программе возможен. Однако даже в Haskell считается хорошим стилем явно
документировать типы функций, хотя в этом языке и возможен полный вывод типов.
Мы считаем, что принудительное объявление типов функций при сохранении
локального вывода типов - это хороший компромисс.

Как насчёт возвращаемого значения? Вот функция, которая прибавляет один к
целому:

```rust
fn add_one(x: i32) -> i32 {
    x + 1
}
```

Функции в Rust возвращают ровно одно значение, тип которого объявляется после
"стрелки". "Стрелка" представляет собой дефис (`-`), за которым следует знак
"больше" (`>`).

Заметьте, что в функции выше нет точки с запятой. Если бы мы добавили этот знак:

```{rust,ignore}
fn add_one(x: i32) -> i32 {
    x + 1;
}
```

Мы бы получили ошибку:

```text
error: not all control paths return a value
fn add_one(x: i32) -> i32 {
     x + 1;
}

help: consider removing this semicolon:
     x + 1;
          ^
```

Помните мы обсуждали точку с запятой и тривиальное значение `()` (unit)? Наша
функция объявлена, как возвращающая `i32`. Но если в конце есть точка с запятой,
функция вернёт тривиальное значение `()`. Компилятор Rust обрабатывает эту
ситуацию и предлагает удалить точку с запятой.

Это очень похоже на оператор `if`: результат блока (`{}`) это результат
выражения. Есть и другие языки программирования, в которых операторы возвращают
значение - например, Ruby; однако, такая логика немного непривычна в мире
системного программирования. Люди, впервые узнающие об этой возможности, часто
считают, что она приводит к появлению ошибок. Однако, во-первых, Rust реализует
строгую типизацию. Во-вторых, тривиальное значение `()` имеет уникальный тип.
Поэтому мы никогда не видели ситуации, в которой добавление или удаление точки с
запятой в позиции возвращаемого значения вызывало бы ошибку.

А что насчёт раннего возврата из функции? У нас есть для этого ключевое слово
`return`:

```rust
fn foo(x: i32) -> i32 {
    if x < 5 { return x; }

    x + 1
}
```

`return` можно написать и в последней строке тела функции, но это считается
плохим стилем:

```rust
fn foo(x: i32) -> i32 {
    if x < 5 { return x; }

    return x + 1;
}
```

Если вы никогда не работали с языком, в котором операторы являются выражениями,
предыдущее определение без `return` может показаться вам странным. Но со
временем вы просто перестанете замечать это. К тому же, если бы это был
настоящий код, мы бы всё равно не написали его так. Этот вариант лучше:

```rust
fn foo(x: i32) -> i32 {
    if x < 5 {
        x
    } else {
        x + 1
    }
}
```

Поскольку оператор `if` является выражением, и это единственное выражение в этой
функции, значением `foo` будет результат оператора `if`.

## Расходящиеся функции

Для функций, которые не возвращают управление ("расходящихся"), в Rust есть
специальный синтаксис:

```
fn diverges() -> ! {
    panic!("Эта функция не возвращает управление!");
}
```

`panic!` - это макрос, как и `println!()`, который мы встречали ранее. В отличие
от `println!()`, `panic!()` вызывает остановку текущего потока исполнения с
заданным сообщением.

Поскольку эта функция вызывает остановку исполнения, она никогда не вернёт
управление. Поэтому тип её возвращаемого значения обозначается знаком `!` и
читается как "расходится". Значение расходящейся функции может быть использовано
как значение любого типа:

```should_panic
# fn diverges() -> ! {
#    panic!("Эта функция никогда не выходит!");
# }

let x: i32 = diverges();
let x: String = diverges();
```

Пока эта возможность выглядит бесполезной. Она приобретает значение в сочетании
с другими возможностями Rust. Но по крайней мере, если вы увидите ` -> !`, вы
будете знать, что это такое.
